### ISSUE TITLE
Epic Story: Compare data from 2 countries and have more ways to visualize data

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#105]
In our continuing saga of Fred, he is using the site daily. What he has found is that he is sometimes opening the site in multiple windows in order to compare data between 2 countries or to compare different types of data. He would love it if the site would give him the ability to have 2 (or more) countries on the same graph. He would also love additional ways to visualize data, eg, different chart types and statistical summaries. This would enable him to obtain the information he needs more quickly to be better informed about COVID data and, ultimately, to win arguments with his friends and on social media. :)

**Comment by bpurbancic** [comment]
- [ ] Change generate_graphs.py to dynamic image creation in order to allow for more chart 

- [ ] Update generate_graphs.py to allow for 2 countries

- [ ] Update html to provide 2 country drop downs

- [ ] Update SQL to improve logic and add country code as primary key to improve ability to use multiple countries

- [ ] Make code more readable in above sections by refactoring and/or adding comments

- [ ] Add ability to display data in different formats, eg, statistical summary by country

**Comment by BlastoiseBlue** [comment]
Uh, item 4 is a no-go for now. A primary key has to be unique within a table, and that becomes an issue when you notice that each country code appears A LOT in the table. Unfortunately, django does not support multi-column primary keys (such as a combination of ISO code and date). I have, however, added an additional column that concatenates the date and the ISO code fields, and used that as a primary key.

**Comment by sjiang1** [comment]
Is this done?

**Comment by bpurbancic** [comment]
The first part is done; the 2nd part has been modified because more was required than simply adding a new chart style.
We have all 3 countries set up to compare charts. And the code is expandable to any number of countries.
To complete the "more ways to visualize data" we have to pull different data. To see the available data, I've added a summary function. Jeff has a task this week to add a bar graph.
