### ISSUE TITLE
Epic Story 3: The Before Times

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#107]
As a daily user of the site, Fred hasn't been thrilled with blog functionality. Load times are slow and the blog seems to be down entirely far too often. Also, other blogs that he frequents have commenting capabilities. He is confident that both his friends will visit the site more frequently and move many of their debates online with these features implemented.

Week ending 10/12:

- [x] Choose appropriate web server that will provide consistent up time (Brian, Emmet, Chisulo) #113 

- [x] Test functionality of chosen web server to ensure compatibility with django and SQL pkg (Chisulo, Emmet, Brian) #114 

Week ending 10/19:

- [x] Launch blog on new web server (Emmet, Chisulo, Brian) #115 

- [x] Add AWS instructions to README (Chisulo, Brian) #125 

- [x] Have AWS server running 24/7 even when terminal is closed (Chisulo) #127
